[package]
name = "linfa_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
kiss3d = "0.35.0"
linfa = "0.7.0"
linfa-clustering = "0.7.0"
linfa-datasets = "0.7.0"
nalgebra = "0.33.0"
ndarray = "0.16.0"
pcd-rs = {version="0.11.1", features=["derive"]}
